### ISSUE TITLE
Breadcrumbs are not displaying arrows on macOS

### ISSUE THREAD

**Issue by sarabveer** [scottlimmer/pfsense-theme-clearblue#3]
For some reason, the arrows in the breadcrumb are not being rendered.

On Safari 17:
<img width="249" alt="image" src="https://github.com/scottlimmer/pfsense-theme-clearblue/assets/4297171/845ab29f-a0ba-4870-8100-de0e0fdc750b">

Chrome 116:
<img width="239" alt="image" src="https://github.com/scottlimmer/pfsense-theme-clearblue/assets/4297171/e16086f4-768a-428d-bf03-5e4b078d327a">

**Comment by scottlimmer** [comment]
Unfortunately, I can't replicate this issue. Breadcrumb arrows are working as expected for me on Chrome 117 (Windows).

Happy to receive more detail to reproduce or a PR

**Comment by sarabveer** [comment]
Just tested on MS Edge 117 on Windows and wasn't able to replicate either.

The initial screenshots I posted are from macOS. I also tested it on Firefox for macOS, same issue. I'll try looking into it a bit.

**Comment by sarabveer** [comment]
I have found out the issue, the breadcrumbs are using the symbol ⮞ (U+2B9E). For some reason, this code point doesn't have a glyph in the macOS system fonts.

https://github.com/scottlimmer/pfsense-theme-clearblue/blob/main/partials/_header.scss#L15C15-L15C15

I guess one solution would be to use another symbol. Does the Nunito Sans font used in theme include this symbol? Another solution would be to use that font-family there if it does include that arrow symbol.

**Comment by sarabveer** [comment]
Just to test it out, I replaced it locally with this symbol: https://www.compart.com/en/unicode/U+27A4

<img width="257" alt="image" src="https://github.com/scottlimmer/pfsense-theme-clearblue/assets/4297171/9fd073b0-6b1b-47ad-a750-f7c171565d00">

**Comment by scottlimmer** [comment]
Nice pickup. I've changed the breadcrumb arrow to use the globally bundled Font Awesome, so that should ensure consistency across platforms. 

Can you test the PR one (hopefully) last time?

**Comment by scottlimmer** [comment]
Thanks for your assistance @sarabveer

**Comment by sarabveer** [comment]
> Thanks for your assistance @sarabveer

No problem, great theme btw!
